### ISSUE TITLE
version.sbt missing? 

### ISSUE THREAD

**Issue by danyaljj** [jeantil/blog-samples#1]
Did you mean to add a `version.sbt` to the repo? 
You seem to be talking about this file in your blog post, but it doesn't exist in the repo
Otherwise, where is the version kept? 

> Set the project’s version to the next development version and write it to the version file.

**Comment by jeantil** [comment]
Hi @danyaljj 

No part of the point of my blog article is to avoid the `version.sbt` file. The line you quote is taken from the paragraph where I detail the default behavior of sbt-release. 

I then go on to explain that the `version.sbt` mechanism is not compatible with what I want (sha1 based versions) 

> With our setup, if we want to be able to repeat a specific version build all we have to do is checkout the corresponding tag which will automatically set the version to the correct value. Additionally, writing the version to an SBT file will kill the SHA-1 based versioning scheme we were using.

The version is defined either by the current SHA-1 (for `snapshot` builds) or by the git tag for the commit. 

Building a check-out of the commit for a given tag will automatically rebuild the artifacts for this version.

**Comment by danyaljj** [comment]
I see I see. makes perfect sense.
