### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by noahlz** [jeantil/blog-samples#2]
I borrowed some of the code you published in your "painless release with sbt" sample, and I would like to publish the results to my own github repo.

What is the license for this code?

https://help.github.com/articles/licensing-a-repository/

**Comment by jeantil** [comment]
Consider all the code Apache 2.0 

I added the license on the master branch, updated the painless sbt build branch.
I will not update the futureOption branches  as it is too much work I have 7 branches for these from my exploration time and I don't even remember which ones are really important. 

I will however be careful for the future branches. 

Please note that this code is only intended as illustration for my blog (blog.byjean.eu) and I don't consider it production ready.  I usually make sure it works when I write the blog post but I don't maintain it once the article is published.
